.TH tap-ctl 8
.SH NAME
tap-ctl \- short desc goes here
.SH SYNOPSIS
.B tap-ctl
.I <COMMAND> [OPTIONS]

.SH COMMANDS
.B list
.B allocate
.B free
.B create
.B destroy
.B spawn
.B attach
.B detach
.B open
.B close
.B pause
.B unpause
.B stats
.B major
.B check

.SH DESCRIPTION
.B lock-util
Long description goes here.
