.TH vhd-util 8

.SH NAME
vhd-util \- short desc goes here

.SH SYNOPSIS
.B vhd-util
.I <COMMAND> [OPTIONS]

.SH COMMANDS
.B create

.B snapshot

.B query

.B read

.B set

.B repair

.B resize

.B fill

.B coalesce

.B modify

.B scan

.B check

.B revert

.SH DESCRIPTION
.B vhd-util
Long description goes here.

.SH OPTIONS

