#!/usr/bin/python
#
# Copyriht (C) Citrix Systems Inc.
#
# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU Lesser General Public License as published 
# by the Free Software Foundation; version 2.1 only.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
# A plugin for enabling thin lvhd on slaves

import sys
import XenAPIPlugin
sys.path.append("/opt/xensource/sm/")
import util
import LVHDSR
import SRCommand
import lvhdutil
import lvutil

def to_xml(d):

    dom = xml.dom.minidom.Document()
    upgrade_response = dom.createElement("upgrade_response")
    dom.appendChild(upgrade_response)

    for key, value in sorted(d.items()):
        key_value_element = dom.createElement("key_value_pair")
        upgrade_response.appendChild(key_value_element)

        key_element = dom.createElement("key")
        key_text_node = dom.createTextNode(key)
        key_element.appendChild(key_text_node)
        key_value_element.appendChild(key_element)

        value_element = dom.createElement("value")
        value_text_mode = dom.createTextNode(value)
        value_element.appendChild(value_text_mode)
        key_value_element.appendChild(value_element)

    return dom.toxml()

def enable_thin_lvhd(session, args):
    util.SMlog("host_ref is %s" % args['host_ref'])
    util.SMlog("sr_ref is %s" % args['sr_ref'])

    try:
        driver_info = LVHDSR.DRIVER_INFO
        cmd = SRCommand.SRCommand(driver_info)

        input_params = {}
        input_params['session_ref'] = session._session
        input_params['host_ref'] = args['host_ref']
        input_params['sr_ref'] = args['sr_ref']
        input_params['command'] = "LVHD.enable_thin_provisioning"
        sr_uuid = session.xenapi.SR.get_uuid(args['sr_ref'])
        input_params['sr_uuid'] = sr_uuid

        pbd_ref = util.find_my_pbd(session, args['host_ref'], args['sr_ref'])
        pbd = session.xenapi.PBD
        device_config = pbd.get_device_config(pbd_ref)
        input_params['device_config'] = device_config
        cmd.dconf = input_params['device_config']
        cmd.dconf['device'] = "/dev/disk/by-id/scsi-"+device_config['SCSIid']
        if util.is_master(session):
            cmd.dconf['SRmaster'] = "true"
        else:
            cmd.dconf['SRmaster'] = "false"
        cmd.params = input_params
        sr = LVHDSR.LVHDSR(cmd, sr_uuid)
        sr.upgrade(sr_uuid)
        return str(True)
    except:
        err_msg = {
            ERROR_CODE_KEY: 'EnableThinProvisionException',
            ERROR_MSG_KEY: 'EnableThinProvisionException: Enabling thin provision failed on SR [%s]'
            % sr_uuid
        }
        result = to_xml(err_msg)
        return result

if __name__ == "__main__":
    XenAPIPlugin.dispatch({
        "enable_thin_lvhd": enable_thin_lvhd})
