#!/usr/bin/python

import sys
import os
import subprocess
import base64

def doexec(args, inputtext=None):
    """Execute a subprocess, then return its return code, stdout and stderr"""
    proc = subprocess.Popen(args,stdin=subprocess.PIPE,stdout=subprocess.PIPE,stderr=subprocess.PIPE,close_fds=True)
    (stdout,stderr) = proc.communicate(inputtext)
    rc = proc.returncode
    return (rc,stdout,stderr)

try:
	cmd = ["/usr/bin/sg_inq", "--page=0xc8", "-r", sys.argv[1]]
	(rc, stdout, stderr) = doexec(cmd)
        if rc == 0:
	    print stdout.encode("hex")[180:212]	
except:
        sys.exit(1)
